### ISSUE TITLE
Cannot find module?

### ISSUE THREAD

**Issue by dagumak** [kriasoft/react-starter-kit#104]
Clean repo, and following the readme yielded the following error:
```
node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206
					throw e;
					      ^
Error: Cannot find module 'to-fast-properties'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/douglasmak/personal/showtracker/node_modules/babel-core/lib/babel/types/index.js:81:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by koistya** [comment]
@dagumak Have you made sure that all the npm modules are installed properly, at least `webpack` in this case? See any error messages during `npm install`?

**Comment by dagumak** [comment]
I got this working after upgrading my node from 0.10.35 to the latest. Same with NPM.

**Comment by ipochi** [comment]
i get the same error , I am on node version 0.12.2 and npm 2.9.0

**Comment by dagumak** [comment]
Try 
```npm cache clean  && npm install ```

**Comment by elkebirmed** [comment]
Just uninstall babel-core and install it again
